"use client";

import Image from "next/image";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { BedDouble, MapPin, SlidersHorizontal } from "lucide-react";
import type { PropertySearchRequest } from "@ghardekho/validation";
import type { ApiListSuccess, PropertyRecord } from "@ghardekho/types";
import { ApiError } from "@/lib/api/client";
import { searchProperties } from "@/lib/api/properties";

const money = (price: string, type: string) => {
  const amount = Number(price);
  const value = amount >= 10_000_000 ? `₹${(amount / 10_000_000).toFixed(amount % 10_000_000 ? 2 : 0)} Cr` : amount >= 100_000 ? `₹${(amount / 100_000).toFixed(amount % 100_000 ? 1 : 0)} L` : `₹${amount.toLocaleString("en-IN")}`;
  return type === "RENT" ? `${value} / month` : value;
};

function PropertyCard({ property }: { property: PropertyRecord }) {
  const photo = property.media?.find((item) => item.isPrimary)?.url ?? property.media?.find((item) => item.type === "IMAGE")?.url;
  return <article className="group overflow-hidden border border-line bg-white transition-shadow hover:shadow-[0_14px_40px_rgba(5,36,29,.11)]">
    <Link href={`/properties/${encodeURIComponent(property.slug)}`} className="block">
      <div className="relative aspect-[1.48] bg-forest-soft">
        {photo ? <Image src={photo} alt={property.media?.find((item) => item.url === photo)?.altText || property.title} fill unoptimized sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw" className="object-cover transition-transform duration-500 group-hover:scale-[1.025]" /> : <div className="grid h-full place-items-center text-sm text-muted">Photos coming soon</div>}
        <span className="absolute left-4 top-4 bg-white/95 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.12em] text-forest">For {property.listingType === "RENT" ? "rent" : "sale"}</span>
      </div>
      <div className="p-5"><p className="text-xl font-semibold tracking-tight text-ink">{money(property.price, property.listingType)}</p><h2 className="mt-2 line-clamp-1 text-[15px] font-semibold text-ink">{property.title}</h2><p className="mt-1 flex items-center gap-1.5 text-sm text-muted"><MapPin size={14}/>{property.locality}, {property.city}</p><div className="mt-5 flex items-center gap-4 border-t border-line pt-4 text-xs text-muted">{property.bedrooms !== null && <span className="flex items-center gap-1.5"><BedDouble size={15}/>{property.bedrooms} bed</span>}<span>{Number(property.area).toLocaleString("en-IN")} {property.areaUnit.toLowerCase()}</span><span className="ml-auto">{property.propertyType.replaceAll("_", " ")}</span></div></div>
    </Link>
  </article>;
}

export function Discovery() {
  const params = useSearchParams();
  const [filters, setFilters] = useState<PropertySearchRequest>(() => ({ city: params.get("city") || undefined, locality: params.get("locality") || undefined, listingType: (params.get("listingType") as PropertySearchRequest["listingType"]) || undefined, propertyType: (params.get("propertyType") as PropertySearchRequest["propertyType"]) || undefined, minPrice: params.has("minPrice") ? Number(params.get("minPrice")) : undefined, maxPrice: params.has("maxPrice") ? Number(params.get("maxPrice")) : undefined, sort: (params.get("sort") as PropertySearchRequest["sort"]) || "newest", page: 1, limit: 12 }));
  const [result, setResult] = useState<ApiListSuccess<PropertyRecord> | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [mobileFilters, setMobileFilters] = useState(false);
  const load = useCallback(async (next: PropertySearchRequest) => { setLoading(true); setError(""); try { setResult(await searchProperties(next)); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "We couldn’t load homes right now."); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => { void load(filters); }, 0); return () => window.clearTimeout(timer); }, [filters, load]);
  const change = (key: keyof PropertySearchRequest, value: string) => setFilters((current) => ({ ...current, page: 1, [key]: value ? (["minPrice", "maxPrice", "bedrooms"].includes(key) ? Number(value) : value) : undefined }));
  const fields = <>
    <label className="grid gap-2 text-xs font-semibold text-muted">City<input value={filters.city ?? ""} onChange={(e) => change("city", e.target.value)} placeholder="Any city" className="h-11 border border-line px-3 text-sm font-normal text-ink"/></label>
    <label className="grid gap-2 text-xs font-semibold text-muted">Listing<select value={filters.listingType ?? ""} onChange={(e) => change("listingType", e.target.value)} className="h-11 border border-line bg-white px-3 text-sm font-normal text-ink"><option value="">Buy or rent</option><option value="SALE">For sale</option><option value="RENT">For rent</option></select></label>
    <label className="grid gap-2 text-xs font-semibold text-muted">Property type<select value={filters.propertyType ?? ""} onChange={(e) => change("propertyType", e.target.value)} className="h-11 border border-line bg-white px-3 text-sm font-normal text-ink"><option value="">All types</option>{[["APARTMENT","Apartment"],["HOUSE","House"],["VILLA","Villa"],["PLOT","Plot"],["COMMERCIAL","Commercial"],["OFFICE","Office"],["SHOP","Shop"],["WAREHOUSE","Warehouse"]].map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select></label>
    <label className="grid gap-2 text-xs font-semibold text-muted">Bedrooms<select value={filters.bedrooms ?? ""} onChange={(e) => change("bedrooms", e.target.value)} className="h-11 border border-line bg-white px-3 text-sm font-normal text-ink"><option value="">Any</option>{[1,2,3,4,5].map((n)=><option key={n} value={n}>{n} BHK</option>)}</select></label>
    <div className="grid grid-cols-2 gap-2"><label className="grid gap-2 text-xs font-semibold text-muted">Min price<input type="number" min="0" value={filters.minPrice ?? ""} onChange={(e)=>change("minPrice",e.target.value)} className="h-11 min-w-0 border border-line px-3 text-sm font-normal text-ink"/></label><label className="grid gap-2 text-xs font-semibold text-muted">Max price<input type="number" min="0" value={filters.maxPrice ?? ""} onChange={(e)=>change("maxPrice",e.target.value)} className="h-11 min-w-0 border border-line px-3 text-sm font-normal text-ink"/></label></div>
    <label className="grid gap-2 text-xs font-semibold text-muted">Furnishing<select value={filters.furnishing ?? ""} onChange={(e)=>change("furnishing",e.target.value)} className="h-11 border border-line bg-white px-3 text-sm font-normal text-ink"><option value="">Any</option><option value="UNFURNISHED">Unfurnished</option><option value="SEMI_FURNISHED">Semi-furnished</option><option value="FURNISHED">Furnished</option></select></label>
  </>;
  return <>
    <div className="border-b border-line bg-paper"><div className="container py-10 sm:py-14"><p className="eyebrow">Thoughtfully found</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em] text-ink sm:text-4xl">Find a place to call home.</h1><p className="mt-3 text-sm text-muted">Explore published homes and properties across India.</p></div></div>
    <div className="container py-8 sm:py-12"><div className="mb-5 flex items-center justify-between gap-3"><p className="text-sm text-muted">{loading ? "Finding homes…" : `${result?.pagination.total ?? 0} homes to explore`}</p><div className="flex items-center gap-2"><button onClick={()=>setMobileFilters(true)} className="flex h-10 items-center gap-2 border border-line px-3 text-sm lg:hidden"><SlidersHorizontal size={16}/>Filters</button><label className="flex h-10 items-center gap-2 border border-line px-3 text-sm text-muted">Sort<select value={filters.sort ?? "newest"} onChange={(e)=>change("sort",e.target.value)} className="bg-white text-ink"><option value="newest">Newest</option><option value="price_asc">Price: low to high</option><option value="price_desc">Price: high to low</option><option value="area">Largest area</option></select></label></div></div>
      <div className="grid gap-8 lg:grid-cols-[250px_1fr]"><aside className="hidden h-fit gap-5 border border-line bg-white p-5 lg:grid"><h2 className="text-base font-semibold">Refine your search</h2>{fields}<button onClick={()=>setFilters({page:1,limit:12,sort:"newest"})} className="text-left text-xs font-semibold text-forest">Clear all filters</button></aside><section aria-live="polite">{error ? <div className="border border-red-200 bg-red-50 p-8 text-center"><h2 className="font-semibold">We couldn’t load these homes</h2><p className="mt-2 text-sm text-muted">{error}</p><button onClick={()=>void load(filters)} className="mt-4 font-semibold text-forest underline">Try again</button></div> : loading && !result ? <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{[0,1,2,3,4,5].map((x)=><div key={x} className="animate-pulse"><div className="aspect-[1.48] bg-paper"/><div className="mt-4 h-5 w-1/2 bg-paper"/></div>)}</div> : result?.data.length ? <><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{result.data.map((property)=><PropertyCard key={property.id} property={property}/>)}</div><div className="mt-9 flex items-center justify-between border-t border-line pt-5"><span className="text-sm text-muted">Page {result.pagination.page} of {Math.max(1,result.pagination.totalPages)}</span><div className="flex gap-2"><button disabled={filters.page===1} onClick={()=>setFilters({...filters,page:Math.max(1,(filters.page??1)-1)})} className="h-10 border border-line px-4 text-sm disabled:opacity-40">Previous</button><button disabled={(filters.page??1)>=result.pagination.totalPages} onClick={()=>setFilters({...filters,page:(filters.page??1)+1})} className="h-10 border border-line px-4 text-sm disabled:opacity-40">Next</button></div></div></> : <div className="border border-line bg-paper px-6 py-16 text-center"><p className="eyebrow">A fresh start</p><h2 className="mt-3 text-xl font-semibold">No homes match just yet.</h2><p className="mt-2 text-sm text-muted">Try broadening your filters to see more places.</p><button onClick={()=>setFilters({page:1,limit:12,sort:"newest"})} className="mt-5 font-semibold text-forest underline">Clear filters</button></div>}</section></div></div>
    {mobileFilters && <div className="fixed inset-0 z-[70] bg-black/40 lg:hidden" onClick={()=>setMobileFilters(false)}><section role="dialog" aria-modal="true" aria-label="Search filters" onClick={(e)=>e.stopPropagation()} className="absolute inset-x-0 bottom-0 max-h-[88vh] overflow-auto bg-white p-6"><div className="mb-5 flex justify-between"><h2 className="text-lg font-semibold">Refine your search</h2><button aria-label="Close filters" onClick={()=>setMobileFilters(false)}>✕</button></div><div className="grid gap-4">{fields}</div><button onClick={()=>setMobileFilters(false)} className="mt-6 h-12 w-full bg-forest font-semibold text-white">Show homes</button></section></div>}
  </>;
}
